In [4]:
import numpy as np
import matplotlib as plt

a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
c = np.array([1,2,3,4,5], ndmin = 2)
d = np.array([1,2,3], dtype=float)
print(a)
print(b)
print(c)
print(d)
print(a[2])

[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[1. 2. 3.]
3


In [6]:
c = np.zeros(5)
d = np.ones(5)

e = np.zeros((5,5))
print(c)
print(d)
print(e)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
a = np.eye(3)
b = np.eye(3, 4)

c = np.linspace(10, 20, 5)
print(a)
print(b)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[10.  12.5 15.  17.5 20. ]


In [13]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)
print(b[2,1])
print(b[:,1])
print(np.shape(b))
print(np.size(b))
print(np.ndim(b))
print(np.transpose(b))

c = np.copy(b)
print(c)
print(np.ravel(c))

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
5
[1 3 5]
(3, 2)
6
2
[[0 2 4]
 [1 3 5]]
[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12], [13,14]])



In [17]:
a = np.array([1.0, 5.55, 123, 0.567, 25.532])
b = np.around(a)
c = np.around(a,decimals=1)
d = np.around(a,decimals=-1)

print(b)
print(c)
print(d)

[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [18]:
b = np.random.rand(3,2)

c = np.random.randint(3, 9, size=(2,4))

print(b)
print(c)

[[0.2033801  0.6044304 ]
 [0.89838709 0.92051013]
 [0.8474306  0.04059583]]
[[4 7 7 3]
 [3 5 8 5]]
